openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths: {}
components:
  schemas:
    FavoriteTweet:
      required:
        - "favorite_tweet"
      properties:
        favorite_tweet:
          type: string

    UnfavoriteTweet:
      required:
        - "unfavorite_tweet"
      properties:
        unfavorite_tweet:
          type: string

    # ---Retweet---
    
    CreateRetweet:
      required:
        - "result"
      properties:
        result:
          type: object
          items:
            $ref: "#/components/schemas/Retweet"
    
    DeleteRetweet:
      required:
        - "result"
      properties:
        result:
          type: object
          items:
            $ref: "#/components/schemas/Retweet"

    Retweet:
      required:
        - "rest_id"
        - "legacy"
      properties:
        rest_id:
          type: string
        legacy:
          type: object
          items:
            properties:
              full_text:
                type: string
    
    # ---Tweet---

    CreateTweet:
      required:
        - "result"
      properties:
        result:
          type: object
          items:
            $ref: "./tweet.yaml#/components/schemas/Tweet"
    
    DeleteTweet:
      properties:
        type: object
        nullable: true