openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /{{FavoriteTweetQuery}}/FavoriteTweet:
    post:
      operationId: favoriteTweet
      description: favorite Tweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FavoriteTweetResponseData"
      tags:
        - "Post"
  
  /{{UnfavoriteTweetQuery}}/UnfavoriteTweet:
    post:
      operationId: unfavoriteTweet
      description: unfavorite Tweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnfavoriteTweetResponseData"
      tags:
        - "Post"

  /{{CreateRetweetQuery}}/CreateRetweet:
    post:
      operationId: createRetweet
      description: create Retweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateRetweetResponse"
      tags:
        - "Post"

  /{{DeleteRetweetQuery}}/DeleteRetweet:
    post:
      operationId: deleteRetweet
      description: delete Retweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteRetweetResponse"
      tags:
        - "Post"

  /{{CreateTweetQuery}}/CreateTweet:
    post:
      operationId: createTweet
      description: create Tweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTweetResponse"
      tags:
        - "Post"

  /{{DeleteTweetQuery}}/DeleteTweet:
    post:
      operationId: deleteTweet
      description: delete Retweet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteTweetResponse"
      tags:
        - "Post"

components:
  schemas:
    FavoriteTweetResponseData:
      required:
        - "data"
      properties:
        data:
          $ref: "./../schemas/post.yaml#/components/schemas/FavoriteTweet"

    UnfavoriteTweetResponseData:
      required:
        - "data"
      properties:
        data:
          $ref: "./../schemas/post.yaml#/components/schemas/UnfavoriteTweet"

    # ---Retweet---

    CreateRetweetResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/CreateRetweetResponseData"

    CreateRetweetResponseData:
      required:
        - "create_retweet"
      properties:
        create_retweet:
          $ref: "#/components/schemas/CreateRetweetResponseResult"

    CreateRetweetResponseResult:
      required:
        - "retweet_results"
      properties:
        retweet_results:
          $ref: "./../schemas/post.yaml#/components/schemas/CreateRetweet"

    DeleteRetweetResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/DeleteRetweetResponseData"

    DeleteRetweetResponseData:
      required:
        - "unretweet"
      properties:
        create_retweet:
          $ref: "#/components/schemas/CreateRetweetResponseResult"

    DeleteRetweetResponseResult:
      required:
        - "source_tweet_results"
      properties:
        retweet_results:
          $ref: "./../schemas/post.yaml#/components/schemas/DeleteRetweet"
    
    # ---Tweet---

    CreateTweetResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/CreateTweetResponseData"

    CreateTweetResponseData:
      required:
        - "create_tweet"
      properties:
        create_retweet:
          $ref: "#/components/schemas/CreateTweetResponseResult"

    CreateTweetResponseResult:
      required:
        - "tweet_results"
      properties:
        tweet_results:
          $ref: "./../schemas/post.yaml#/components/schemas/CreateTweet"
    
    DeleteTweetResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/DeleteTweetResponseData"

    DeleteTweetResponseData:
      required:
        - "delete_tweet"
      properties:
        delete_retweet:
          $ref: "#/components/schemas/DeleteTweetResponseResult"

    DeleteTweetResponseResult:
      required:
        - "tweet_results"
      properties:
        tweet_results:
          $ref: "./../schemas/post.yaml#/components/schemas/DeleteTweet"